### ISSUE TITLE
`lein repl` fails

### ISSUE THREAD

**Issue by flow-tiago** [flowyourmoney/malli-graphql#5]
```
WARNING: It appears your project does not contain a ClojureScript dependency. One will be provided for you by lein-cljsbuild, but it is strongly recommended that you add your own.  You can find a list of all ClojureScript releases here:
http://search.maven.org/#search|gav|1|g%3A%22org.clojure%22%20AND%20a%3A%22clojurescript%22


Compiling ["out/main.js"] from ["src"]...
Compiling ["out/main.js"] failed.
clojure.lang.ExceptionInfo:  {:tag :cljs/analysis-error}
        at clojure.core$ex_info.invoke(core.clj:4327)
        at cljs.analyzer$error.invoke(analyzer.clj:380)
        at cljs.analyzer$analyze.invoke(analyzer.clj:1944)
        at cljs.analyzer$parse_ns$fn__2041$fn__2042.invoke(analyzer.clj:2074)
        at cljs.analyzer$parse_ns$fn__2041.invoke(analyzer.clj:2074)
        at cljs.analyzer$parse_ns.invoke(analyzer.clj:2055)
        at cljs.analyzer$parse_ns.invoke(analyzer.clj:2046)
        at cljs.compiler$compile_root$fn__3163.invoke(compiler.clj:1170)
        at clojure.core$map$fn__4207.invoke(core.clj:2487)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$map$fn__4207.invoke(core.clj:2479)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
        at clojure.core.protocols$fn__6026.invoke(protocols.clj:54)
        at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6177)
        at cljs.js_deps$build_index.invoke(js_deps.clj:126)
        at cljs.js_deps$dependency_order.invoke(js_deps.clj:166)
        at cljs.compiler$compile_root.invoke(compiler.clj:1171)
        at cljs.closure$compile_dir.invoke(closure.clj:378)
        at cljs.closure$eval3525$fn__3526.invoke(closure.clj:418)
        at cljs.closure$eval3461$fn__3462$G__3452__3469.invoke(closure.clj:325)
        at cljs.closure$eval3512$fn__3513.invoke(closure.clj:432)
        at cljs.closure$eval3461$fn__3462$G__3452__3469.invoke(closure.clj:325)
        at cljs.build.api$inputs$reify__3893$compile_input__3894.invoke(api.clj:110)
        at clojure.core$map$fn__4207.invoke(core.clj:2485)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$apply.invoke(core.clj:617)
        at clojure.core$mapcat.doInvoke(core.clj:2514)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at cljs.build.api$inputs$reify__3893._compile(api.clj:114)
        at cljs.closure$build.invoke(closure.clj:1446)
        at cljs.closure$build.invoke(closure.clj:1404)
        at cljs.build.api$build.invoke(api.clj:119)
        at cljsbuild.compiler$compile_cljs$fn__4310.invoke(compiler.clj:61)
        at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:60)
        at cljsbuild.compiler$run_compiler.invoke(compiler.clj:168)
        at user$eval4425$iter__4461__4465$fn__4466$fn__4484.invoke(form-init4267408837371712309.clj:1)
        at user$eval4425$iter__4461__4465$fn__4466.invoke(form-init4267408837371712309.clj:1)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$dorun.invoke(core.clj:2780)
        at clojure.core$doall.invoke(core.clj:2796)
        at user$eval4425.invoke(form-init4267408837371712309.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6619)
        at clojure.lang.Compiler.eval(Compiler.java:6609)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.Compiler.loadFile(Compiler.java:7020)
        at clojure.main$load_script.invoke(main.clj:294)
        at clojure.main$init_opt.invoke(main.clj:299)
        at clojure.main$initialize.invoke(main.clj:327)
        at clojure.main$null_opt.invoke(main.clj:362)
        at clojure.main$main.doInvoke(main.clj:440)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
        at cljs.core$import_macros$fn__4554.invoke(core.clj:54)
        at clojure.core$map$fn__4207.invoke(core.clj:2485)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$map$fn__4211.invoke(core.clj:2490)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:67)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$concat$cat__3925$fn__3926.invoke(core.clj:687)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:598)
        at clojure.lang.Compiler.eval(Compiler.java:6606)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5018.invoke(core.clj:5530)
        at clojure.core$load.doInvoke(core.clj:5529)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at cljs.analyzer$load_core.invoke(analyzer.clj:320)
        at cljs.analyzer$analyze$fn__2013.invoke(analyzer.clj:1950)
        at cljs.analyzer$analyze.invoke(analyzer.clj:1946)
        ... 66 more
```

**Comment by flow-tiago** [comment]
Commenting this out from `project.clj` makes it work:
```
  ;; :plugins [[lein-cljsbuild "1.1.8"]]

  ;; :cljsbuild {:builds [{:source-paths ["src"]
  ;;                       :compiler {:output-to "out/main.js"
  ;;                                  :optimization :advanced}}]}

  ;; :hooks [leiningen.cljsbuild]
  ```
  
  Shouldn't we use only shadow-cljs for cljs?
